exports.DEFAULT_LANGUAGE_RATE = 3.00
exports.DOWNLOAD_URL_EXPIRE_DAYS = 2
exports.USER_JWT_EXPIRE_DAYS = '2d'
exports.ADMIN_JWT_EXPIRE_DAYS = '2d'
exports.CGST_RATE = 9.00
exports.SGST_RATE = 9.00
